### ISSUE TITLE
liquidmetal failure for some (non-ASCII?) strings

### ISSUE THREAD

**Issue by abingham** [bcse/stringscore#3]
It appears that `liquidmetal.score` throws an `IndexError` for some kinds of input. This seems to be related to non-ASCII inputs, but that may be a red herring. 

For example, this fails:
```
liquidmetal.score('İ', 'İ')
``` 

See #2 for more details.

**Comment by bcse** [comment]
I think I have found the root cause.

```
>>> len('İ')
1
>>> len('İ'.lower())
2
```

In Python 3, 'İ'.lower() returns 'i̇' and the length is 2. It's 'i' + '̇'.
The algorithm mostly using lower case as normalized form to do comparing. But it need to check if the character is upper case with the original string.

I'm not sure how to properly handle this issue. Here are some options:

1. Use upper case as normalized form instead of lower case?
No. Because the upper case of 'ß' is 'SS'.

2. Remove all combining diacritical marks from lower case string?
Maybe. The result will change, could be better or worse, it depends.

3. Actually handle combining diacritical marks?
I tend not to. That would be a lot of work.

I think I will go with 2. Do you have any ideas?

**Comment by abingham** [comment]
FWIW, I think you should be using [casefold](https://docs.python.org/3/library/stdtypes.html#str.casefold) for correct unicode-aware case-insensitive matching. But as you say, this doesn't really address the key issue of upper-case checks.

I'm not in a great position to say which of those options it the best. I think (1) is not necessary with casefold, but I don't know the details of your algorithm well enough to say what the impact of (2) or (3) would be. Certainly (3) sounds more "correct", but if it has a large performance impact and doesn't offer better results than (2), then it's clearly incorrect. 

I don't really know how you're assessing the quality of the matches - intuition, heuristics, research, or what - so I'm afraid I can't be much concrete help. My hunch, though, is that you're correct about going with (2). If that's easy to do, make the change and see if anyone complains ;)

**Comment by bcse** [comment]
Actually, I thought nobody use this library. So I'm curious, what's your use case of stringscore? Looks like you are using it to matching URLs?

**Comment by abingham** [comment]
Exactly. I'm working on a website for converting HTML5-based presentations (e.g. reveal.js, slidy, etc.) into PDFs. As people enter URLs for conversion, I offer them matches from the database of existing conversions that they can use instead (i.e. to avoid the time needed for a new conversion). I use liquidmetal to compare the entered URL fragments to existing URLs.

To be honest, stringscore was the first library I found after I abandoned a simple levenshtein-based solution. It works well enough that I haven't looked for alternatives.
